-- Remove the placeholder stub tests of the starter subject ("Биология").
--
-- The stubs ("Тест N — Вопрос M", options "Ответ A".."Ответ D") were
-- temporary filler for validating the mechanics. Real content is generated
-- by AI (DeepSeek), so the stubs are deleted together with their questions
-- and any user progress on them. Deleting tests cascades to test_questions,
-- test_attempts and attempt_questions; the orphaned questions and their
-- user_question_progress rows are removed explicitly.
DELETE FROM user_question_progress
WHERE question_id IN (
    SELECT q.id
    FROM questions q
    JOIN subjects s ON s.id = q.subject_id
    WHERE s.name = 'Биология' AND q.topic = 'Заглушка'
);

DELETE FROM questions
WHERE subject_id IN (SELECT id FROM subjects WHERE name = 'Биология')
  AND topic = 'Заглушка';

-- The stub tests themselves. SAFETY GUARD: only EMPTY tests are deleted
-- (no linked questions at all). A chain test that already has questions —
-- e.g. generated by AI while this migration was pending — is real content
-- and must survive. This migration is recorded in schema_migrations and runs
-- exactly once; it never deletes anything on later startups.
DELETE FROM tests t
WHERE t.subject_id IN (SELECT id FROM subjects WHERE name = 'Биология')
  AND t.kind = 'chain'
  AND t.test_number <= 3
  AND NOT EXISTS (SELECT 1 FROM test_questions tq WHERE tq.test_id = t.id);
