-- R-6: questions of tests generated by the worker AFTER the quality audit
-- existed (migration 000011) already passed repairFlagged before they were
-- stored, but were written with quality_checked_at = NULL, so the sweep
-- re-audited them. Mark exactly those as checked. Careful condition:
--   * the test was produced by a 'done' generation job finished after
--     000011 was applied (the audit ran in runJob);
--   * the test is not a clone (origin_test_id IS NULL) — a clone may copy a
--     legacy, never-audited source;
--   * the question has no failed repairs / postponement.
-- Everything else stays NULL for the sweep. Idempotent (only NULL rows).
UPDATE questions q
SET quality_checked_at = now()
WHERE q.quality_checked_at IS NULL
  AND q.quality_attempts = 0
  AND q.quality_postponed_until IS NULL
  AND EXISTS (
      SELECT 1
      FROM test_questions tq
      JOIN tests t ON t.id = tq.test_id
      JOIN generation_jobs j ON j.test_id = t.id
      WHERE tq.question_id = q.id
        AND t.origin_test_id IS NULL
        AND j.status = 'done'
        AND j.updated_at > (SELECT applied_at FROM schema_migrations WHERE version = 11)
  );
