package services

// Fingerprint templates — «identical tests for identical weak topics»
// (audit item 2): a test generated by AI for one input fingerprint is
// stored once (test_templates) and CLONED — new tests row + new question
// rows with the same content — for every further request with the same
// fingerprint, with no AI call:
//
//   - personal tests: fingerprint = subject + sorted weak-topic keys. The
//     clone path runs when the shared question bank can not assemble the
//     test (EnsurePersonalTest) and again inside a personal job (a template
//     may have appeared while the job waited). A user never receives the
//     same template twice (test_template_uses); a repeated request with the
//     same weak topics generates a new VARIANT, which then serves others.
//   - chain tests: fingerprint = subject + chain position + previous test +
//     weak topics. A chain test is already shared by every student, so this
//     only saves the regeneration of a chain slot with identical inputs
//     (a revived/re-queued job, a test deactivated and requested again).
//     GEN_TEMPLATE_REUSE=false disables reuse (e.g. when a chain test was
//     removed on purpose to get a different one).
//
// Cloned questions keep quality_checked_at (they passed the audit when the
// template was generated) and their catalog topic_key; cached Kazakh
// translations of the template's source test are copied (zero AI calls).

import (
	"context"
	"log"
	"sync"
	"time"

	"github.com/Bihan293/Juz40tester/internal/metrics"
	"github.com/Bihan293/Juz40tester/internal/models"
	"github.com/Bihan293/Juz40tester/internal/repositories"
)

func (g *GeneratorService) templateReuse() bool {
	return g.cfg == nil || g.cfg.GenTemplateReuse || g.cfg.GenStrategy == ""
}

// cloneFromTemplate serves a job from a stored template. ok=false: no
// usable template (generate normally).
func (g *GeneratorService) cloneFromTemplate(ctx context.Context, job *models.GenerationJob, fingerprint, title string, ownerUserID int64) (int64, bool) {
	if fingerprint == "" || !g.templateReuse() || g.gen == nil {
		return 0, false
	}
	tpl, err := g.gen.FindTemplate(ctx, job.SubjectID, job.Kind, fingerprint, ownerUserID)
	if err != nil {
		log.Printf("generator: job %d: template lookup: %v", job.ID, err)
		return 0, false
	}
	if tpl == nil {
		return 0, false
	}
	var test *models.Test
	var qids []int64
	switch job.Kind {
	case models.TestKindPersonal:
		test, qids, err = g.gen.ClonePersonalFromTemplate(ctx, tpl, ownerUserID, title)
	case models.TestKindChain:
		test, err = g.gen.CloneChainFromTemplate(ctx, tpl, job.TestNumber, title)
	default:
		return 0, false
	}
	if err != nil {
		log.Printf("generator: job %d: clone template %d: %v", job.ID, tpl.ID, err)
		return 0, false
	}
	g.afterClone(ctx, tpl, ownerUserID, test, qids)
	if r := genRunFrom(ctx); r != nil {
		r.templateHit = true
		r.strategy, r.kind = strategyTemplate, job.Kind
	}
	if job.ID > 0 {
		_ = g.gen.SetJobStrategy(ctx, job.ID, strategyTemplate)
	}
	log.Printf("generator: job %d (%s) served by template %d (fingerprint %s) -> test %d, no AI call", job.ID, job.Kind, tpl.ID, fingerprint, test.ID)
	return test.ID, true
}

// afterClone records the use, carries translations over and counts metrics.
func (g *GeneratorService) afterClone(ctx context.Context, tpl *repositories.TestTemplate, userID int64, test *models.Test, qids []int64) {
	if err := g.gen.MarkTemplateUsed(ctx, tpl.ID, userID, test.ID); err != nil {
		log.Printf("generator: mark template %d used: %v", tpl.ID, err)
	}
	if g.translator != nil && tpl.SourceTestID > 0 && len(qids) > 0 {
		if n, err := g.translator.CopyTranslationsToTest(ctx, tpl.SourceTestID, qids); err != nil {
			log.Printf("generator: copy translations template %d -> test %d: %v", tpl.ID, test.ID, err)
		} else if n > 0 {
			log.Printf("generator: carried %d cached translation(s) to cloned test %d", n, test.ID)
		}
	}
	metrics.Inc(metrics.TemplateHits, "kind", tpl.Kind)
}

// saveTemplate stores a freshly generated test as a template of its
// fingerprint and records that its owner already received it.
func (g *GeneratorService) saveTemplate(ctx context.Context, job *models.GenerationJob, fingerprint string, testNumber int, topics []string, seed []models.SeedQuestion, testID, ownerUserID int64, strategy string) {
	if fingerprint == "" || g.gen == nil {
		return
	}
	tpl := &repositories.TestTemplate{
		SubjectID: job.SubjectID, Kind: job.Kind, Fingerprint: fingerprint,
		TestNumber: testNumber, Topics: topics, Questions: seed,
		SourceTestID: testID, Strategy: strategy,
	}
	if _, err := g.gen.SaveTemplate(ctx, tpl); err != nil {
		log.Printf("generator: job %d: save template: %v", job.ID, err)
		return
	}
	if ownerUserID > 0 {
		if err := g.gen.MarkTemplateUsed(ctx, tpl.ID, ownerUserID, testID); err != nil {
			log.Printf("generator: job %d: mark template used: %v", job.ID, err)
		}
	}
	metrics.Inc(metrics.TemplateSaves, "kind", job.Kind)
}

// clonePersonalForUser is the EnsurePersonalTest fast path: a template of
// the user's weak-topics fingerprint exists → the user gets a clone
// immediately (no queue, no AI, no daily-limit charge).
func (g *GeneratorService) clonePersonalForUser(ctx context.Context, userID, subjectID int64, keys []string) *models.Test {
	if !g.templateReuse() || g.gen == nil {
		return nil
	}
	fp := models.WeakTopicsFingerprint(subjectID, keys)
	tpl, err := g.gen.FindTemplate(ctx, subjectID, models.TestKindPersonal, fp, userID)
	if err != nil {
		log.Printf("generator: personal template lookup user %d subject %d: %v", userID, subjectID, err)
		return nil
	}
	if tpl == nil {
		return nil
	}
	test, qids, err := g.gen.ClonePersonalFromTemplate(ctx, tpl, userID, personalTestTitle)
	if err != nil {
		log.Printf("generator: clone template %d for user %d: %v", tpl.ID, userID, err)
		return nil
	}
	g.afterClone(ctx, tpl, userID, test, qids)
	log.Printf("generator: personal test %d for user %d cloned from template %d (fingerprint %s), no AI call", test.ID, userID, tpl.ID, fp)
	return test
}

// ---------------------------------------------------------------------------
// Subject-wide weak topics cache
// ---------------------------------------------------------------------------

const (
	// subjectWeakWindow: only students active within this window count.
	subjectWeakWindow = 30 * 24 * time.Hour
	// subjectWeakMinUsers: a topic needs this many classified students.
	subjectWeakMinUsers = 3
	// subjectWeakTTL: cache lifetime of the aggregate per subject.
	subjectWeakTTL = 10 * time.Minute
)

type subjectWeakEntry struct {
	at     time.Time
	titles []string
}

type subjectWeakCacheT struct {
	mu sync.Mutex
	m  map[int64]subjectWeakEntry
}

var subjectWeakCache = &subjectWeakCacheT{m: map[int64]subjectWeakEntry{}}

func (c *subjectWeakCacheT) get(id int64) ([]string, bool) {
	c.mu.Lock()
	defer c.mu.Unlock()
	e, ok := c.m[id]
	if !ok || time.Since(e.at) > subjectWeakTTL {
		return nil, false
	}
	return e.titles, true
}

func (c *subjectWeakCacheT) put(id int64, titles []string) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.m[id] = subjectWeakEntry{at: time.Now(), titles: titles}
}

// ---------------------------------------------------------------------------
// Strategy outcome (A/B)
// ---------------------------------------------------------------------------

// recordOutcome writes the job outcome to metrics + gen_strategy_stats.
func (g *GeneratorService) recordOutcome(ctx context.Context, r *genRun, done bool, d time.Duration) {
	if r == nil {
		return
	}
	result := "failed"
	if done {
		result = "done"
	}
	metrics.Inc(metrics.Jobs, "kind", r.kind, "strategy", r.strategy, "result", result)
	if g.gen == nil {
		return
	}
	o := repositories.StrategyOutcome{
		Strategy: r.strategy, Kind: r.kind, Done: done,
		AICalls: int(r.calls.Load()), AIRejects: int(r.rejects.Load()),
		DifficultyViolations: int(r.diffViolation.Load()), RepeatRejects: int(r.repeats.Load()),
		TemplateHit: r.templateHit, PromptTokens: int(r.promptTok.Load()), CompletionTokens: int(r.complTok.Load()),
		Duration: d,
	}
	if err := g.gen.RecordStrategyOutcome(ctx, g.now(), o); err != nil {
		log.Printf("generator: record strategy outcome: %v", err)
	}
	log.Printf("genstats strategy=%s kind=%s result=%s ai_calls=%d rejects=%d difficulty_violations=%d repeats=%d tokens_in=%d tokens_out=%d dur=%.1fs",
		r.strategy, r.kind, result, o.AICalls, o.AIRejects, o.DifficultyViolations, o.RepeatRejects, o.PromptTokens, o.CompletionTokens, d.Seconds())
}
